import type { Metadata } from "next";
import "../globals.css";
import { ReactQueryClientProvider } from "@/components/QueryProvider";
import SolanaWalletProvider from "../providers";
import Navbar from "../_components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <ReactQueryClientProvider>
        <SolanaWalletProvider>
          <Navbar />
          {children}
        </SolanaWalletProvider>
      </ReactQueryClientProvider>
    </main>
  );
}
